# Generated by Django 3.0 on 2020-11-07 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('fist_term', 'FIRST TERM'), ('second_term', 'SECOND TERM'), ('third_term', 'THIRD TERM')], max_length=100)),
                ('session', models.CharField(choices=[('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022')], max_length=100)),
                ('math_exan', models.FloatField(null=True)),
                ('math_test', models.FloatField(null=True)),
                ('math_total', models.FloatField(null=True)),
                ('math_grade', models.CharField(max_length=10)),
                ('eng_exan', models.FloatField(null=True)),
                ('eng_test', models.FloatField(null=True)),
                ('eng_total', models.FloatField(null=True)),
                ('eng_grade', models.CharField(max_length=10)),
                ('physics_exan', models.FloatField(null=True)),
                ('physics_test', models.FloatField(null=True)),
                ('physics_total', models.FloatField(null=True)),
                ('physics_grade', models.CharField(max_length=10)),
                ('bio_exan', models.FloatField(null=True)),
                ('bio_test', models.FloatField(null=True)),
                ('bio_total', models.FloatField(null=True)),
                ('bio_grade', models.CharField(max_length=10)),
                ('chem_exan', models.FloatField(null=True)),
                ('chem_test', models.FloatField(null=True)),
                ('chem_total', models.FloatField(null=True)),
                ('chem_grade', models.CharField(max_length=10)),
                ('agric_exan', models.FloatField(null=True)),
                ('agric_test', models.FloatField(null=True)),
                ('agric_total', models.FloatField(null=True)),
                ('agric_grade', models.CharField(max_length=10)),
                ('civic_exan', models.FloatField(null=True)),
                ('civic_test', models.FloatField(null=True)),
                ('civic_total', models.FloatField(null=True)),
                ('civic_grade', models.CharField(max_length=10)),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Students')),
            ],
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
