# Generated by Django 3.0 on 2020-11-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20201108_0509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='agric_exan',
            new_name='agric_exam',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='bio_exan',
            new_name='bio_exam',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='chem_exan',
            new_name='chem_exam',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='civic_exan',
            new_name='civic_exam',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='eng_exan',
            new_name='eng_exam',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='physics_exan',
            new_name='physics_exam',
        ),
    ]
